dist: xenial
language: python
sudo: false

branches:
  only:
  - master

python:
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - ./setup.py test
  - ./run_integration_tests.py
